/* SPDX-License-Identifier: GPL-2.0-only */

/*
 * First pass, decoded from the stock BIOS via inteltool.
 * TODO: owner/route/reset refinements.
 */

#include <southbridge/intel/lynxpoint/lp_gpio.h>

const struct pch_lp_gpio_map mainboard_lp_gpio_map[] = {
	[0]  = LP_GPIO_NATIVE,
	[1]  = LP_GPIO_NATIVE,
	[2]  = LP_GPIO_NATIVE,
	[3]  = LP_GPIO_NATIVE,
	[4]  = LP_GPIO_NATIVE,
	[5]  = LP_GPIO_NATIVE,
	[6]  = LP_GPIO_NATIVE,
	[7]  = LP_GPIO_NATIVE,
	[8]  = LP_GPIO_INPUT,
	[9]  = { .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL },
	[10] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[11] = LP_GPIO_NATIVE,
	[12] = LP_GPIO_NATIVE,
	[13] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[14] = LP_GPIO_OUT_HIGH,
	[15] = LP_GPIO_INPUT,
	[16] = LP_GPIO_INPUT,
	[17] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_LOW,
	       .conf1 = GPIO_SENSE_DISABLE },
	[18] = LP_GPIO_NATIVE,
	[19] = LP_GPIO_NATIVE,
	[20] = LP_GPIO_INPUT,
	[21] = LP_GPIO_NATIVE,
	[22] = LP_GPIO_NATIVE,
	[23] = LP_GPIO_NATIVE,
	[24] = LP_GPIO_OUT_LOW,
	[25] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[26] = LP_GPIO_INPUT,
	[27] = LP_GPIO_INPUT,
	[28] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[29] = LP_GPIO_NATIVE,
	[30] = LP_GPIO_NATIVE,
	[31] = LP_GPIO_INPUT,
	[32] = LP_GPIO_NATIVE,
	[33] = LP_GPIO_NATIVE,
	[34] = LP_GPIO_NATIVE,
	[35] = LP_GPIO_NATIVE,
	[36] = LP_GPIO_NATIVE,
	[37] = LP_GPIO_NATIVE,
	[38] = LP_GPIO_NATIVE,
	[39] = LP_GPIO_NATIVE,
	[40] = LP_GPIO_NATIVE,
	[41] = LP_GPIO_NATIVE,
	[42] = LP_GPIO_NATIVE,
	[43] = LP_GPIO_NATIVE,
	[44] = LP_GPIO_INPUT,
	[45] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[46] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[47] = LP_GPIO_INPUT_INVERT,
	[48] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_LOW,
	       .conf1 = GPIO_SENSE_DISABLE },
	[49] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[50] = { .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL },
	[51] = LP_GPIO_INPUT,
	[52] = LP_GPIO_INPUT,
	[53] = LP_GPIO_INPUT,
	[54] = LP_GPIO_INPUT,
	[55] = LP_GPIO_INPUT,
	[56] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[57] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_LOW,
	       .conf1 = GPIO_SENSE_DISABLE },
	[58] = { .conf0 = GPIO_MODE_GPIO | GPIO_DIR_INPUT | GPIO_IRQ_LEVEL },
	[59] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[60] = LP_GPIO_NATIVE,
	[61] = LP_GPIO_NATIVE,
	[62] = LP_GPIO_NATIVE,
	[63] = LP_GPIO_NATIVE,
	[64] = LP_GPIO_NATIVE,
	[65] = LP_GPIO_NATIVE,
	[66] = LP_GPIO_INPUT,
	[67] = LP_GPIO_NATIVE,
	[68] = LP_GPIO_NATIVE,
	[69] = LP_GPIO_NATIVE,
	[70] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_LOW,
	       .conf1 = GPIO_SENSE_DISABLE },
	[71] = LP_GPIO_NATIVE,
	[72] = LP_GPIO_INPUT,
	[73] = LP_GPIO_NATIVE,
	[74] = LP_GPIO_NATIVE,
	[75] = LP_GPIO_NATIVE,
	[76] = LP_GPIO_NATIVE,
	[77] = LP_GPIO_INPUT,
	[78] = LP_GPIO_INPUT,
	[79] = LP_GPIO_INPUT,
	[80] = LP_GPIO_INPUT,
	[81] = LP_GPIO_NATIVE,
	[82] = LP_GPIO_NATIVE,
	[83] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_LOW,
	       .conf1 = GPIO_SENSE_DISABLE },
	[84] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_LOW,
	       .conf1 = GPIO_SENSE_DISABLE },
	[85] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_LOW,
	       .conf1 = GPIO_SENSE_DISABLE },
	[86] = LP_GPIO_INPUT,
	[87] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_LOW,
	       .conf1 = GPIO_SENSE_DISABLE },
	[88] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[89] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_HIGH,
	       .conf1 = GPIO_SENSE_DISABLE },
	[90] = { .conf0 = GPIO_MODE_GPIO | GPO_LEVEL_LOW,
	       .conf1 = GPIO_SENSE_DISABLE },
	[91] = LP_GPIO_NATIVE,
	[92] = LP_GPIO_NATIVE,
	[93] = LP_GPIO_NATIVE,
	[94] = LP_GPIO_NATIVE,
	LP_GPIO_END
};
