BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nuc-bios"
BBFILE_PATTERN_nuc-bios = "^${LAYERDIR}/"
BBFILE_PRIORITY_nuc-bios = "10"

LAYERSERIES_COMPAT_nuc-bios = "scarthgap"
